### ISSUE TITLE
Env variables in tests should not be hidden if possible

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#563]
We have a bunch of env variables here that actually don't need to be set as secrets or might not be need for tests.
having them as secrets makes it harder to work with outside collaborators on this project since the secrets are not available for test runs from forks.

```yaml
# Do the tests actually use the apis?
NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}

# The next one will be deprecated with the migration to supabase
NEXT_PUBLIC_USER_DATA_API_URL: ${{ secrets.NEXT_PUBLIC_USER_DATA_API_URL }}

# the next three will be deprecated with the migration to supabase
NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}
NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
NEXT_PUBLIC_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}

# Do the tests fail if the next two are not set properly?
NEXT_PUBLIC_MAPBOX_TREES_TILESET_LAYER: ${{ secrets.MAPBOX_TREES_TILESET_LAYER }}
NEXT_PUBLIC_MAPBOX_TREES_TILESET_URL: ${{ secrets.NEXT_PUBLIC_MAPBOX_TREES_TILESET_URL }}
# Can be public as it is not a secret
NEXT_PUBLIC_MAP_BOUNDING_BOX: ${{ secrets.NEXT_PUBLIC_MAP_BOUNDING_BOX }}

# Do the tests fail if the next one is not set properly?
NEXT_PUBLIC_MAPBOX_API_KEY: ${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}

# Can be public as it is not a secret
NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

# Can be public as it is not a secret
NEXT_TELEMETRY_DISABLED: ${{ secrets.NEXT_TELEMETRY_DISABLED }}
```

See https://github.com/technologiestiftung/giessdenkiez-de/blob/8712722b3b33f4d4bdf175a4d016a4ccee20ec51/.github/workflows/test.yml#L7-L17

@dnsos @vogelino What do you say about this. Can we make these values public or replace them with dummy values?
